--- #YAML:1.0
name:                Bundle-Complete-Catalyst
version:             0.03
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.35
distribution_type:   module
requires:     
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
